### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Vector-Kolesnikoff/kinozal-template-project#1]
Нет скруглений
![image](https://user-images.githubusercontent.com/8464662/62720660-20444200-ba13-11e9-807d-74ac8cd24e3d.png)

отступы не соответствуют
![image](https://user-images.githubusercontent.com/8464662/62720702-38b45c80-ba13-11e9-8e80-5262fedec69c.png)

от этих замечаний надо избавиться
![image](https://user-images.githubusercontent.com/8464662/62720803-7a450780-ba13-11e9-9d4b-1d09cbcbea6e.png)

**Comment by Vector-Kolesnikoff** [comment]
Всё исправил! Можете проверить!

чт, 8 авг. 2019 г. в 19:33, Andrey <notifications@github.com>:
